### ISSUE TITLE
Research the possibility of having Web deploy previews

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-teams#7]
# Problem

For someone to perform manual testing a web PR, they have to set up the whole project just for it. This can be cumbersome, and difficult for someone not used to deal with setting up coding projects.

# Idea

So we wish to have a service that allows us to have Pull Request deploy previews.
This would help majorly testers and developers, to not just review code.
This would look like: having a link per PR that has the latest code of the project plus the code from the PR.

# Examples

You can look at this example of a project that has this: https://github.com/thepracticaldev/dev.to
Look in the PRs and you should see they have a check in the bottom with the deploy preview.

# Resources

Useful services:
- Netlify - https://www.netlify.com/
- Heroku - https://heroku.com/

**Comment by sakshivij** [comment]
I have checked. We can do this very easily with netlify. Will update on the steps to implement this soon.

**Comment by isabelcosta** [comment]
thank you so much for your research on this @sakshivij 👏 in such a short time 🎉

**Comment by isabelcosta** [comment]
@sakshivij I just discovered that Heroku also has. Since I have the project deployed there, I will check if this is easily done.

https://devcenter.heroku.com/articles/github-integration-review-apps

![image](https://user-images.githubusercontent.com/11148726/84191202-0e4a8a00-aa90-11ea-9da7-b04895056680.png)

**Comment by sakshivij** [comment]
Awesome! 🙌

**Comment by isabelcosta** [comment]
Uh, but I think I have to upgrade. Let me check Netlify ;) I want something that comes for open source projects for free.

**Comment by sakshivij** [comment]
Netlify is free.

**Comment by sakshivij** [comment]
I'll research a bit more on this after some time if it's required. Since both are different platforms they obviously have different ways they work. I want to be sure which platform is better. 

Would link a document about the research I do for this.

**Comment by isabelcosta** [comment]
thank you again for the research you already did 🙌
I just assigned this to you, to give you credit for your work here! Feel free to focus on other issues if you prefer. I am also working on this :)

**Comment by isabelcosta** [comment]
@sakshivij I managed to do this deploy preview from one PR from my fork repository w/ Heroku 🎉  Netlify, was kind of difficult since that is used for static websites and not server like projects. 

- Deploy Preview: https://to-test-revi-430-update-imlbuk.herokuapp.com/
- PR: https://github.com/isabelcosta/mentorship-backend/pull/2

You can view the deployment link.

![image](https://user-images.githubusercontent.com/11148726/84200029-fbd74d00-aa9d-11ea-86cb-33140b30e582.png)

@anitab-org/qa-team 🤗  🎉 
I still have to do this for mentorship-backend, not only my fork. So some work yet left to do :)

**Comment by isabelcosta** [comment]
This is done 🎉 This requires me to choose wisely which Heroku Review apps to deploy, due to the limit of apps I can have on heroku with a free account.

Right now we already have a deploy preview for this PR on mentorship backend https://github.com/anitab-org/mentorship-backend/pull/552.
Here's the deploy link: https://ms-backend-review-pr-552.herokuapp.com/

I will close this now since this is done
